name: Push Events
on: 
  push:
    branches:
      - master
      - main
      - test
jobs: 
  show-other-info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push event all the branches"
