name: Another Workflow Tets
on: 
  issues:
    types:
      -opened
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
     - name: Info from Workflow
       run: |
         echo "This ia Workflow Test"
    
