name: Another Workflow Tets
on: 
  push: 
    branches:
      - master
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
     - name: Info from Workflow
       run: |
         echo "This ia Workflow Test"
    
